<?php

namespace ContainerL0tvCjP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WadqCr3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WadqCr3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WadqCr3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'oficioRepository' => ['privates', 'App\\Repository\\OficioRepository', 'getOficioRepositoryService', true],
        ], [
            'oficioRepository' => 'App\\Repository\\OficioRepository',
        ]);
    }
}
