<?php

namespace ContainerL0tvCjP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GdSE5tMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gdSE5tM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gdSE5tM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'oficioRepo' => ['privates', 'App\\Repository\\OficioRepository', 'getOficioRepositoryService', true],
            'correspondenceRepo' => ['privates', 'App\\Repository\\CorrespondenceRepository', 'getCorrespondenceRepositoryService', true],
            'circularRepo' => ['privates', 'App\\Repository\\CircularRepository', 'getCircularRepositoryService', true],
            'scannerRepo' => ['privates', 'App\\Repository\\ScannerRepository', 'getScannerRepositoryService', true],
        ], [
            'oficioRepo' => 'App\\Repository\\OficioRepository',
            'correspondenceRepo' => 'App\\Repository\\CorrespondenceRepository',
            'circularRepo' => 'App\\Repository\\CircularRepository',
            'scannerRepo' => 'App\\Repository\\ScannerRepository',
        ]);
    }
}
