<?php

namespace ContainerL0tvCjP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCircularControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qk6e.4i.App\Controller\CircularController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qk6e.4i.App\\Controller\\CircularController::edit()'] = ($container->privates['.service_locator.qk6e.4i'] ?? $container->load('get_ServiceLocator_Qk6e_4iService'))->withContext('App\\Controller\\CircularController::edit()', $container);
    }
}
