<?php

namespace ContainerL0tvCjP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMainControllerdashboardService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gdSE5tM.App\Controller\MainController::dashboard()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gdSE5tM.App\\Controller\\MainController::dashboard()'] = ($container->privates['.service_locator.gdSE5tM'] ?? $container->load('get_ServiceLocator_GdSE5tMService'))->withContext('App\\Controller\\MainController::dashboard()', $container);
    }
}
