<?php

namespace ContainerL0tvCjP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOficioControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Vk9IqOD.App\Controller\OficioController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Vk9IqOD.App\\Controller\\OficioController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'oficio' => ['privates', 'App\\Entity\\Oficio', 'getOficioService', true],
        ], [
            'oficio' => 'App\\Entity\\Oficio',
        ]))->withContext('App\\Controller\\OficioController::show()', $container);
    }
}
