<?php

namespace ContainerL0tvCjP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOficioControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bwgYNH4.App\Controller\OficioController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bwgYNH4.App\\Controller\\OficioController::edit()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'oficio' => ['privates', 'App\\Entity\\Oficio', 'getOficioService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'normalizer' => ['privates', 'App\\Service\\PathNormalizer', 'getPathNormalizerService', true],
        ], [
            'oficio' => 'App\\Entity\\Oficio',
            'em' => '?',
            'normalizer' => 'App\\Service\\PathNormalizer',
        ]))->withContext('App\\Controller\\OficioController::edit()', $container);
    }
}
