<?php

namespace ContainerL0tvCjP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOficioService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Entity\Oficio' shared autowired service.
     *
     * @return \App\Entity\Oficio
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Entity/Oficio.php';

        return $container->privates['App\\Entity\\Oficio'] = new \App\Entity\Oficio();
    }
}
