<?php

namespace ContainerL0tvCjP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOficioControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WadqCr3.App\Controller\OficioController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WadqCr3.App\\Controller\\OficioController::index()'] = ($container->privates['.service_locator.WadqCr3'] ?? $container->load('get_ServiceLocator_WadqCr3Service'))->withContext('App\\Controller\\OficioController::index()', $container);
    }
}
