<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Scanner extends \App\Entity\Scanner implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'fecha_subida' => [parent::class, 'fecha_subida', null, 16],
        "\0".parent::class."\0".'file_path' => [parent::class, 'file_path', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'mime_type' => [parent::class, 'mime_type', null, 16],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null, 16],
        "\0".parent::class."\0".'num_documento' => [parent::class, 'num_documento', null, 16],
        "\0".parent::class."\0".'size' => [parent::class, 'size', null, 16],
        "\0".parent::class."\0".'source_id' => [parent::class, 'source_id', null, 16],
        "\0".parent::class."\0".'source_type' => [parent::class, 'source_type', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'tipo_documento' => [parent::class, 'tipo_documento', null, 16],
        "\0".parent::class."\0".'updated_at' => [parent::class, 'updated_at', null, 16],
        "\0".parent::class."\0".'url_archivo' => [parent::class, 'url_archivo', null, 16],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null, 16],
        'created_at' => [parent::class, 'created_at', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'fecha_subida' => [parent::class, 'fecha_subida', null, 16],
        'file_path' => [parent::class, 'file_path', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'mime_type' => [parent::class, 'mime_type', null, 16],
        'name' => [parent::class, 'name', null, 16],
        'num_documento' => [parent::class, 'num_documento', null, 16],
        'size' => [parent::class, 'size', null, 16],
        'source_id' => [parent::class, 'source_id', null, 16],
        'source_type' => [parent::class, 'source_type', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'tipo_documento' => [parent::class, 'tipo_documento', null, 16],
        'updated_at' => [parent::class, 'updated_at', null, 16],
        'url_archivo' => [parent::class, 'url_archivo', null, 16],
        'user' => [parent::class, 'user', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
