<?php

namespace ContainerTn5MUzA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCisaeTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\CisaeType' shared autowired service.
     *
     * @return \App\Form\CisaeType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/CisaeType.php';

        return $container->privates['App\\Form\\CisaeType'] = new \App\Form\CisaeType();
    }
}
