<?php

namespace ContainerTn5MUzA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCisaeControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ey6PxgW.App\Controller\CisaeController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ey6PxgW.App\\Controller\\CisaeController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cisaeRepo' => ['privates', 'App\\Repository\\CisaeRepository', 'getCisaeRepositoryService', true],
        ], [
            'cisaeRepo' => 'App\\Repository\\CisaeRepository',
        ]))->withContext('App\\Controller\\CisaeController::index()', $container);
    }
}
