<?php

namespace ContainerTn5MUzA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMainControllerdashboardService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Uro6Xe9.App\Controller\MainController::dashboard()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Uro6Xe9.App\\Controller\\MainController::dashboard()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'oficioRepo' => ['privates', 'App\\Repository\\OficioRepository', 'getOficioRepositoryService', true],
            'correspondenceRepo' => ['privates', 'App\\Repository\\CorrespondenceRepository', 'getCorrespondenceRepositoryService', true],
            'circularRepo' => ['privates', 'App\\Repository\\CircularRepository', 'getCircularRepositoryService', true],
            'notaRepo' => ['privates', 'App\\Repository\\NotaInformativaRepository', 'getNotaInformativaRepositoryService', true],
            'scannerRepo' => ['privates', 'App\\Repository\\ScannerRepository', 'getScannerRepositoryService', true],
        ], [
            'oficioRepo' => 'App\\Repository\\OficioRepository',
            'correspondenceRepo' => 'App\\Repository\\CorrespondenceRepository',
            'circularRepo' => 'App\\Repository\\CircularRepository',
            'notaRepo' => 'App\\Repository\\NotaInformativaRepository',
            'scannerRepo' => 'App\\Repository\\ScannerRepository',
        ]))->withContext('App\\Controller\\MainController::dashboard()', $container);
    }
}
