<?php

namespace ContainerTn5MUzA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getScannerControllernewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1llpiLz.App\Controller\ScannerController::new()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1llpiLz.App\\Controller\\ScannerController::new()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
            'oficioRepo' => ['privates', 'App\\Repository\\OficioRepository', 'getOficioRepositoryService', true],
            'corrRepo' => ['privates', 'App\\Repository\\CorrespondenceRepository', 'getCorrespondenceRepositoryService', true],
            'circularRepo' => ['privates', 'App\\Repository\\CircularRepository', 'getCircularRepositoryService', true],
        ], [
            'em' => '?',
            'slugger' => '?',
            'oficioRepo' => 'App\\Repository\\OficioRepository',
            'corrRepo' => 'App\\Repository\\CorrespondenceRepository',
            'circularRepo' => 'App\\Repository\\CircularRepository',
        ]))->withContext('App\\Controller\\ScannerController::new()', $container);
    }
}
