<?php

namespace ContainerTn5MUzA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WkfvUVe.App\Controller\UserController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WkfvUVe.App\\Controller\\UserController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'user' => ['privates', 'App\\Entity\\User', 'getUserService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'user' => 'App\\Entity\\User',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\UserController::delete()', $container);
    }
}
