<?php

namespace ContainerIuyuLuq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCisaeControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RaQrvy5.App\Controller\CisaeController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RaQrvy5.App\\Controller\\CisaeController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cisae' => ['privates', 'App\\Entity\\Cisae', 'getCisaeService', true],
            'oficioRepo' => ['privates', 'App\\Repository\\OficioRepository', 'getOficioRepositoryService', true],
        ], [
            'cisae' => 'App\\Entity\\Cisae',
            'oficioRepo' => 'App\\Repository\\OficioRepository',
        ]))->withContext('App\\Controller\\CisaeController::show()', $container);
    }
}
