<?php

namespace ContainerIuyuLuq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCisaeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Entity\Cisae' shared autowired service.
     *
     * @return \App\Entity\Cisae
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Entity/Cisae.php';

        return $container->privates['App\\Entity\\Cisae'] = new \App\Entity\Cisae();
    }
}
