<?php

namespace ContainerIuyuLuq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCalendarioControllereventosService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RcWFSd2.App\Controller\CalendarioController::eventos()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RcWFSd2.App\\Controller\\CalendarioController::eventos()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'oficioRepo' => ['privates', 'App\\Repository\\OficioRepository', 'getOficioRepositoryService', true],
            'corrRepo' => ['privates', 'App\\Repository\\CorrespondenceRepository', 'getCorrespondenceRepositoryService', true],
            'circularRepo' => ['privates', 'App\\Repository\\CircularRepository', 'getCircularRepositoryService', true],
            'cisaeRepo' => ['privates', 'App\\Repository\\CisaeRepository', 'getCisaeRepositoryService', true],
        ], [
            'oficioRepo' => 'App\\Repository\\OficioRepository',
            'corrRepo' => 'App\\Repository\\CorrespondenceRepository',
            'circularRepo' => 'App\\Repository\\CircularRepository',
            'cisaeRepo' => 'App\\Repository\\CisaeRepository',
        ]))->withContext('App\\Controller\\CalendarioController::eventos()', $container);
    }
}
