<?php

namespace ContainerRx7bXym;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WIWrVaxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wIWrVax' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wIWrVax'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'circularRepository' => ['privates', 'App\\Repository\\CircularRepository', 'getCircularRepositoryService', true],
        ], [
            'circularRepository' => 'App\\Repository\\CircularRepository',
        ]);
    }
}
