<?php

namespace ContainerRx7bXym;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCircularControllerexportService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wIWrVax.App\Controller\CircularController::export()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wIWrVax.App\\Controller\\CircularController::export()'] = ($container->privates['.service_locator.wIWrVax'] ?? $container->load('get_ServiceLocator_WIWrVaxService'))->withContext('App\\Controller\\CircularController::export()', $container);
    }
}
