<?php

namespace ContainerRx7bXym;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCorrespondenceControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Y3PSe9z.App\Controller\CorrespondenceController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Y3PSe9z.App\\Controller\\CorrespondenceController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'correspondence' => ['privates', 'App\\Entity\\Correspondence', 'getCorrespondenceService', true],
        ], [
            'correspondence' => 'App\\Entity\\Correspondence',
        ]))->withContext('App\\Controller\\CorrespondenceController::show()', $container);
    }
}
