<?php

namespace ContainerRx7bXym;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCircularService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Entity\Circular' shared autowired service.
     *
     * @return \App\Entity\Circular
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Entity/Circular.php';

        return $container->privates['App\\Entity\\Circular'] = new \App\Entity\Circular();
    }
}
