<?php

namespace ContainerRx7bXym;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCorrespondenceControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bQMqwPN.App\Controller\CorrespondenceController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bQMqwPN.App\\Controller\\CorrespondenceController::index()'] = ($container->privates['.service_locator.bQMqwPN'] ?? $container->load('get_ServiceLocator_BQMqwPNService'))->withContext('App\\Controller\\CorrespondenceController::index()', $container);
    }
}
