<?php

namespace ContainerRx7bXym;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCircularControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Vxe5qiC.App\Controller\CircularController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Vxe5qiC.App\\Controller\\CircularController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'circular' => ['privates', 'App\\Entity\\Circular', 'getCircularService', true],
        ], [
            'circular' => 'App\\Entity\\Circular',
        ]))->withContext('App\\Controller\\CircularController::show()', $container);
    }
}
