<?php

namespace ContainerRx7bXym;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMainControllerdashboardService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..0uFPIZ.App\Controller\MainController::dashboard()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..0uFPIZ.App\\Controller\\MainController::dashboard()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\OficioRepository', 'getOficioRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\OficioRepository',
        ]))->withContext('App\\Controller\\MainController::dashboard()', $container);
    }
}
