<?php

namespace ContainerRx7bXym;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPathNormalizerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\PathNormalizer' shared autowired service.
     *
     * @return \App\Service\PathNormalizer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/PathNormalizer.php';

        return $container->privates['App\\Service\\PathNormalizer'] = new \App\Service\PathNormalizer(($container->privates['parameter_bag'] ??= new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container)));
    }
}
