<?php

namespace ContainerRx7bXym;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getScannerControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tG81k7P.App\Controller\ScannerController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tG81k7P.App\\Controller\\ScannerController::index()'] = ($container->privates['.service_locator.tG81k7P'] ?? $container->load('get_ServiceLocator_TG81k7PService'))->withContext('App\\Controller\\ScannerController::index()', $container);
    }
}
